##### Day2 concepts
- files
- modules and packages
- Introduction to DA

In [1]:
file=open("first.txt",'r')
print(file.read())
file.close()

This is my day1 session of DA workshop conducted by APSSDC.
Working with files.


In [3]:
with open("first.txt",'r') as data:
    print(data.read()) # str
    data.close()

This is my day1 session of DA workshop conducted by APSSDC.
Working with files.


In [5]:
# readlines
py=open("first.py",'r')
print(py.readlines())
py.close()

['def is_even(n):\n', '    if n%2==0:\n', '        return True\n', '    else:\n', '        return False\n', '    \n', 'is_even(10)']


In [6]:
with open('first.py') as file:
    for line in file.readlines():
        print(line,end="")

def is_even(n):
    if n%2==0:
        return True
    else:
        return False
    
is_even(10)

In [2]:
f=open("second.txt",'r')
print(f.read())
f.close()

This is day2 session 
continued with files concept
file and file operations



In [7]:
# readlines
with open("second.txt",'r') as f2:
    print(f2.readlines())

['This is day2 session \n', 'continued with files concept\n', 'file and file operations\n']


In [8]:
# write() but it overwrites the existed file
wr=open("second.txt",'w')
wr.write("trying to add new content but old data is erased..!")
wr.close()

In [9]:
# append() is the mode 
op=open("second.txt",'a') 
op.write("!..adding new content..!")
op.close()

In [10]:
# we can create the new file using write()
new=open("new.py",'w')
new.write("print('file is created using write()')")
new.close()

In [11]:
# r+ mode is used for both read() and write() at a time
both=open("first.txt",'r+')
print(both.read())
both.write("working r+ mode which is used for both read&write")
both.close()

This is my day1 session of DA workshop conducted by APSSDC.
Working with files.


In [16]:
# write a python program to open the .py file
# find the no.of alphabets,special chars,words and no.of lines
data=open("new.py",'r')
chc=spc=dc=wdc=lc=0
for line in data.readlines():
    for word in line:
        for ch in word:
            if ch.isalpha():
                chc+=1
            elif ch.isdigit():
                dc+=1
            else:
                spc+=1
        wdc+=1
    lc+=1
print("No.of alphabets=",chc)
print("No.of special chars=",spc)
print("No.of digits=",dc)
print("No.of words=",wdc)
print("No.of lines=",lc)

No.of alphabets= 95
No.of special chars= 110
No.of digits= 9
No.of words= 214
No.of lines= 12


#### Modules and Packages
- collection/group of statements called as function
- collection of functions called as module(python)
- collection of modules called as package(java)

In [17]:
import package

In [20]:
from package import fmodule,smodule

In [21]:
print(dir(fmodule))

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'factorial', 'is_even', 'is_perfect']


In [22]:
print(dir(smodule))

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'is_palindrome', 'string_methods']


In [23]:
help(fmodule.factorial)

Help on function factorial in module package.fmodule:

factorial(n)
    #is_even(n)



In [24]:
fmodule.factorial(5)

120

In [25]:
fmodule.is_even(11)

False

In [26]:
fmodule.is_perfect(6)

True

In [27]:
for v in range(1,1000):
    if fmodule.is_perfect(v):
        print(v,end=" ")

6 28 496 

In [28]:
help(smodule.string_methods)

Help on function string_methods in module package.smodule:

string_methods(st, ch)



In [29]:
smodule.string_methods("I am frOM APSSdc located at TadePALLi",'a')

string starts with False
no.of chars= 4
i am from apssdc located at tadepalli
I AM FROM APSSDC LOCATED AT TADEPALLI
I Am From Apssdc Located At Tadepalli
I am from apssdc located at tadepalli
i AM FRom apssDC LOCATED AT tADEpallI


#### Introduction to Data Analysis
- information stored in a file called as a data
- The study of data is called data science
- Machine Learning and Artificial Intelligence are the parts of DS
- Analysis the data/dataset
- **Modules of Data Science**
    1. Numpy
        - Numerical Python used for scientific computation of data
        - numpy stores the data in array format
        - array() is the sub module of numpy
        - array() is the homogenous data structure allows only one type of data
    2. Pandas
    3. Matplot library
    4. Scikit Learn
    5. Seaborn

In [30]:
import numpy as var

In [31]:
print(dir(var))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [32]:
help(var.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [41]:
# 1dimensional array
print(var.array((3,4,5,6,7,8)))
# tuple/list/set/str/dict
print(var.array([3,4,5,'h'])) # homogenous
print(var.array(range(10,25)))
print(var.array({'st':('anusha','Bhavya'),
                 'dept':['CSE','AIML']}))
print(var.array({9,4,5,6,10,23,45,7,10}))

[3 4 5 6 7 8]
['3' '4' '5' 'h']
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
{'st': ('anusha', 'Bhavya'), 'dept': ['CSE', 'AIML']}
{4, 5, 6, 7, 9, 10, 45, 23}


In [44]:
# creating 2d arrays
ar=var.array([[1,2,3],[4,5,6]],dtype=float)
print(ar)

[[1. 2. 3.]
 [4. 5. 6.]]


In [49]:
ar2=var.array([[1,2,3],[6.3,4.3,5]],dtype=complex)
print(ar2)

[[1. +0.j 2. +0.j 3. +0.j]
 [6.3+0.j 4.3+0.j 5. +0.j]]


In [52]:
# we can create 32 dimensional array
print(var.array([5,6,12,34,90],ndmin=10,dtype=str))

[[[[[[[[[['5' '6' '12' '34' '90']]]]]]]]]]


In [57]:
print(ar.dtype)
print(ar.size)
print(ar.shape)
print(ar.itemsize)
print(ar.ndim) # 

float64
6
(2, 3)
8
2


#### funtions that supports to create arrays
- arange()
- ones()
- zeros()
- full()
- fill()
- linspace()
- diag()
- identity()
- eye()
- random()
- reshape()

In [59]:
print(var.arange(10,25))
print(var.arange(20,78,4))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[20 24 28 32 36 40 44 48 52 56 60 64 68 72 76]


In [63]:
# convert the above 1d array into ->2d &3d arrays
arn=var.arange(45).reshape(5,9)  #2d
#45-->(1,45),(3,15),(5,9) and vice-versa
print(arn)
#(45)->(3,15)->(3,3,5) or(3,5,3)
ar3=var.arange(45).reshape(3,5,3) # (n,r,c)
print(ar3)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]]


In [68]:
print(var.ones(4)) # 1d
print(var.ones((4,5),dtype=int)) #2d

[1. 1. 1. 1.]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [69]:
print(var.zeros(5))
print(var.zeros((3,3)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [73]:
print(var.full(4,9))
fl=var.full((4,4),5)
print(fl)
fl.fill(8)
fl

[9 9 9 9]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [74]:
#diag
var.diag([4,5,6,9])

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 9]])

In [79]:
r=var.arange(96).reshape(3,-1)
print(r)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55
  56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87
  88 89 90 91 92 93 94 95]]


In [80]:
r2=var.arange(78).reshape(-4,3)
print(r2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]
 [36 37 38]
 [39 40 41]
 [42 43 44]
 [45 46 47]
 [48 49 50]
 [51 52 53]
 [54 55 56]
 [57 58 59]
 [60 61 62]
 [63 64 65]
 [66 67 68]
 [69 70 71]
 [72 73 74]
 [75 76 77]]


In [81]:
#diagongal values of 5x5
var.diag(var.arange(25).reshape(5,5))

array([ 0,  6, 12, 18, 24])

In [85]:
#linspace:linear space:linearly separating the given range
#giving the 50 distribution values by default 
print(var.linspace(3,8,20).reshape(4,5)) # both limits are inclusive

[[3.         3.26315789 3.52631579 3.78947368 4.05263158]
 [4.31578947 4.57894737 4.84210526 5.10526316 5.36842105]
 [5.63157895 5.89473684 6.15789474 6.42105263 6.68421053]
 [6.94736842 7.21052632 7.47368421 7.73684211 8.        ]]


In [83]:
#3,4,5,6,7,8:
6/50

0.12

#### random
- random is the sub module of numpy which is used to generate random values 
- var.random.random()
- var.random.rand()
- var.random.randf()
- var.random.randn()
- var.random.randint()
- var.random.randint(,)
- var.random.randint(,,)


In [87]:
print(var.random.random((3,4))) # 

[[0.16419457 0.62711548 0.9791671  0.57320297]
 [0.13719103 0.69792903 0.92329102 0.64796869]
 [0.76417168 0.21233463 0.78827988 0.44390696]]


In [91]:
print(dir(var.random))

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'PCG64DXSM', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'tria

In [93]:
print(var.random.ranf((4,3)))

[[0.88607642 0.27891905 0.56443569]
 [0.128779   0.22734368 0.20214076]
 [0.42687402 0.16917827 0.81139254]
 [0.74611903 0.03872187 0.34179242]]


In [94]:
print(var.random.rand(3,3))

[[0.34410698 0.88143867 0.05695597]
 [0.98211918 0.66937472 0.15068737]
 [0.77979953 0.91841271 0.25211525]]


In [95]:
print(var.random.randn(3,3))

[[ 0.14567745  0.23139934  0.5962566 ]
 [-0.38387953 -0.77728679  1.43476434]
 [-0.5232866   1.80320546 -0.38282196]]


In [100]:
print(var.random.randint(100000))
print(var.random.randint(100,4565))
print(var.random.randint(100,300,900).reshape(9,10,10))# (lw,up,n)

61162
3994
[[[172 230 218 101 242 248 161 220 107 259]
  [100 285 234 173 137 250 225 152 259 119]
  [117 223 242 181 147 171 158 274 110 109]
  [146 171 262 192 299 120 294 199 234 242]
  [179 196 168 238 283 295 253 239 120 104]
  [278 280 237 224 230 259 159 106 114 259]
  [194 102 225 156 181 169 161 153 255 160]
  [185 140 101 116 164 189 101 269 154 283]
  [254 149 162 182 294 220 268 144 226 180]
  [274 180 231 154 195 168 110 236 246 201]]

 [[223 280 134 214 111 286 262 185 209 290]
  [298 223 170 236 275 194 268 139 102 139]
  [228 236 294 257 198 100 212 159 211 282]
  [254 124 181 195 197 151 255 101 230 128]
  [276 265 277 109 148 111 186 264 181 168]
  [180 254 160 224 142 198 154 234 131 198]
  [210 143 111 108 254 272 272 286 102 227]
  [131 292 108 227 183 158 169 205 131 245]
  [129 283 247 268 199 103 138 197 226 288]
  [230 185 266 192 102 258 231 225 155 100]]

 [[145 196 249 100 103 270 239 267 191 171]
  [195 115 289 262 256 165 187 222 196 151]
  [136 109 242 11

##### array indexing and slicing
- 2types
    1. formal indexing
        - 2ways
            1. forward/+ve indexing
                - starts from 0 to len(it)-1
                - travers from left to right
            2. backward/-ve indexing
                - starts from right to left
                - -1 to -infinite
    2. fancy indexing
        - condition based indexing

In [101]:
ran=var.random.randint(100,300,25).reshape(5,5)
ran

array([[154, 121, 253, 168, 109],
       [299, 179, 149, 199, 169],
       [148, 264, 278, 143, 294],
       [209, 191, 139, 263, 230],
       [117, 253, 122, 293, 276]])

In [102]:
# array which satisfy the condition
ran>250

array([[False, False,  True, False, False],
       [ True, False, False, False, False],
       [False,  True,  True, False,  True],
       [False, False, False,  True, False],
       [False,  True, False,  True,  True]])

In [105]:
ran[ran>250].reshape(3,3)

array([[253, 299, 264],
       [278, 294, 263],
       [253, 293, 276]])